### ISSUE TITLE
The difference between calculations for weighted center across replicates or samples 

### ISSUE THREAD

**Issue by dangdachang** [ay-lab/dcHiC#61]
Hello, I'm confused that the calculations for getting weighted center across replicates or samples should be different when considering the cumulative normal distribution probability associated with the maximum z-score, according to your paper published in Nature communications. But in the code, the calculations are same. Is there something wrong?
![image](https://user-images.githubusercontent.com/29725415/226656805-2637aa06-f986-4ea0-8674-cae8685536b8.png)
In details, the codes in dchicf.r  lines 767-769 and lines 782-784 are same for replicate and sample.

**Comment by ay-lab** [comment]
The weighted centers provide more weight to the points distant from others among the samples (further from the diagonal) than to points closer together in the multidimensional space (close to the diagonal). While for replicates, this approach provides more weight to the features closer to each other within replicates of a sample (close to the diagonal) than the calculation across different samples. Although this code looks the same and will give more weight to the points distant from others (or maybe the opposite), the Chi-square p-value calculated from the mahalanobis distance is rectified for this. The lower tail p-values are estimated for replicates, while for samples, it is changed to the upper tail (lower.tail=T/F option in pchisq). This has the same effect as that of multiplying the replicate positions with (df * df_pval_max) instead of (df * 1-df_pval_max) and keeping the pchisq lower.tail option is the same for both cases.

**Comment by ay-lab** [comment]
So for your first question, it uses the highest Z-score per HiC bins (i) across samples to calculate the weight. So, it tries to penalize all the points (HiC bins) distant from others based on that particular outlier Z-score from one sample. For your second query, if you look at the pnorm function, I have set the lower.tail option to True. The equation in the paper is written assuming the weight is calculated setting lower.tail to False (so that you penalize more with a higher Z-score), but in the code it was set to True. so I have used (1 - df_pval_max) to calculate the weight. Basically, if the Z-score is, let's say 2 then `pnorm(2, lower.tail=T) is  0.9772499` and `pnorm(2, lower.tail=F) is 0.02275013`. I am just then using `1 - pnorm(2, lower.tail=T)` to obtain the weight. So, `weight = pnorm(Zscore, lower.tail=F) = (1-pnorm(2, lower.tail=T))`. A mahalanobis distance is ultimately related to the use of lower or upper tails in pchisq in the sense of how we will interpret it. A large mahalnobis distance with upper tail pchisq will give a low significance value meaning that it is an outlier in the sample space.

**Comment by dangdachang** [comment]
Thanks a lot for answering my questions. Additionally, I have another question. The original Mahalanobis distance can be expressed as a sum of variables following a standard normal distribution. Thus, it can be regarded as a chi-squared statistic and tested for significance using a chi-squared test. However, in your modified version of the Mahalanobis distance, the mean of all data points has not been subtracted. Can it still be used as a chi-squared statistic and tested for significance using a chi-squared test?

**Comment by dangdachang** [comment]
Thanks a lot for your answer. But I think the compartment scores are calculated from the distance-normalized Z-transformed correlation matrix, maybe not the interaction matrix. And the compartment scores are PC1 values, the interaction matrix with (mean=0, sd=1)  may not guarantee that they have a mean value of 0. Maybe I can check the mean value of compartment scores later. Thank you and I have no more questions.
